package com.yildiz.terapinisec.util;

public enum Specialization {
    CHILD_PSYCHOLOGY,
    FAMILY_THERAPY,
    TRAUMA_THERAPY,
    ANXIETY_DISORDER,
    DEPRESSION_TREATMENT,
    COGNITIVE_BEHAVIORAL_THERAPY,
    COUPLE_THERAPY,
    STRESS_MANAGEMENT,
    GRIEF_COUNSELING,
    ADDICTION_RECOVERY,
    OCD_TREATMENT,
    ADHD_MANAGEMENT,
    EATING_DISORDER_TREATMENT,
    SLEEP_DISORDER_TREATMENT,
    SEXUAL_HEALTH_COUNSELING,
    CAREER_COUNSELING,
    POSTPARTUM_SUPPORT,
    SOCIAL_ANXIETY_MANAGEMENT,
    ANGER_MANAGEMENT,
    EMOTIONAL_REGULATION
}
